apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 4008
      targetPort: 4008
