apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: default
  labels:
    app: auth-service
  annotations:
      # Sobe logo após do banco de dados no argoCD  
    argocd.argoproj.io/sync-wave: "0"  
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: carlosalves77/auth-service:0.0.5
          imagePullPolicy: Always
          ports:
            - containerPort: 4005
              protocol: TCP
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx192m -XX:+UseSerialGC"
            - name: SERVER_PORT
              value: "4005"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: "org.hibernate.dialect.PostgreSQLDialect"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092" 
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secrets
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi 
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
