apiVersion: v1
kind: Service
metadata:
  name: postgres-auth
  namespace: default
  labels:
    app: postgres-auth
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  clusterIP: None  
  selector:
    app: postgres-auth
