apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deploy
  namespace: default
  labels:
    app: api-gateway
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway-container
          image: carlosalves77/api-gateway:0.0.5
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
              protocol: TCP
          env:
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:4005"
            - name: SERVER_PORT
              value: "4000"
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx256m -XX:+UseSerialGC"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
