apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: shopping-cart
  ports:
    - protocol: TCP
      port: 4006
      targetPort: 4006
