apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-service
  namespace: default
  labels:
    app: shopping-cart
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: shopping-cart
  template:
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
        - name: shopping-cart-service
          image: carlosalves77/shopping-cart-service:0.0.5
          imagePullPolicy: Always
          ports:
            - containerPort: 4006
              protocol: TCP
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx192m -XX:+UseSerialGC"
            - name: SERVER_PORT
              value: "4006"
            - name: SPRING_REDIS_HOST
              value: "redis"
            - name: SPRING_REDIS_PORT
              value: "6379"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,prometheus"
            - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
              value: "true"
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: shopping-cart-secrets
                  key: jwt-secret
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
