apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: orders-service
  ports:
    - protocol: TCP
      port: 4009
      targetPort: 4009
