apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: product-catalog-service
  ports:
    - protocol: TCP
      port: 4004
      targetPort: 4004
