apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-service
  namespace: default
  labels:
    app: product-catalog-service
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: product-catalog-service
  template:
    metadata:
      labels:
        app: product-catalog-service
    spec:
      containers:
        - name: product-catalog-service
          image: carlosalves77/product-catalog-service:0.0.5
          imagePullPolicy: Always
          ports:
            - containerPort: 4004
              protocol: TCP
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx192m -XX:+UseSerialGC"
            - name: SERVER_PORT
              value: "4004"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_OPEN_IN_VIEW
              value: "false"
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: "org.hibernate.dialect.PostgreSQLDialect"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,prometheus"
            - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
              value: "true"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: product-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: product-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-db-secret
                  key: postgres-password
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: product-db-secret
                  key: jwt-secret-key
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
